# Linear Algebra

## Vector Operation

In [0]:
# Library
import numpy as np

# Vector
a = np.array([1, 2])
b = np.array([2, 3])

In [3]:
# Summation
c = a + b
print(c)

c = np.add(a,b)
print(c)

[3 5]
[3 5]


In [4]:
# Subtraction
c = a - b
print(c)

c = np.subtract(a, b)
print(c)

[-1 -1]
[-1 -1]


In [5]:
# Scalar multiplication
c = 2 * a
print(c)

c = np.multiply(2, a)
print(c)

[2 4]
[2 4]


In [6]:
# Inner product
c = np.dot(a, b)
print(c)

c = np.inner(a, b)
print(c)

8
8


## Vector Norm & Inner Product

In [0]:
import numpy as np
from scipy.spatial import distance

# Vector
a = np.array([3, 4])

In [10]:
# 2nd-order norm
norma = np.linalg.norm(a)
print(norma)

5.0


In [11]:
# Euclidean distance between two vectors
a = np.array([3, 4])
b = np.array([3, 2])
print(distance.euclidean(a, b))
print(np.linalg.norm(a-b))

2.0
2.0


In [12]:
# Orthogonal
a = np.array([2, 0])
b = np.array([0, 3])
print(np.inner(a, b))

0


## Matrix Operation

In [0]:
# library
import numpy as np

# Matrix
A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 3], [4, 5]])

In [15]:
# Addition
print(A+B)
print(np.add(A, B))

[[3 5]
 [7 9]]
[[3 5]
 [7 9]]


In [16]:
# Subtraction
print(A-B)
print(np.subtract(A, B))

[[-1 -1]
 [-1 -1]]
[[-1 -1]
 [-1 -1]]


In [17]:
# Scalar Multiplication
print(2*A)
print(np.multiply(2, A))

[[2 4]
 [6 8]]
[[2 4]
 [6 8]]


In [18]:
# Transpose
A = np.mat([[1, 2], [3, 4]])
print(A)
print(A.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [19]:
# Matrix Multiplcation
A = np.matrix([[0, 2, 0, 2], [1, 0, 1, 0]])
B = np.mat([[1], [2], [3], [4]])

print(A@B) # only python 3
print(np.matmul(A, B))
print(np.matmul(B, A))

[[12]
 [ 4]]
[[12]
 [ 4]]


ValueError: ignored

## Various Square Matrix

In [20]:
# Diagonal matrix
diagA = np.diag([1, 2, 4])
print(diagA)

[[1 0 0]
 [0 2 0]
 [0 0 4]]


In [21]:
# Identity matrix
idenA = np.identity(3)
print(idenA)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [22]:
# Triangular matrix
A = np.mat([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print('Square matrix')
print(A)
print('Upper Triangular matrix')
print(np.triu(A))
print('Lower Triangular matrix')
print(np.tril(A))

Square matrix
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Upper Triangular matrix
[[1 2 3]
 [0 5 6]
 [0 0 9]]
Lower Triangular matrix
[[1 0 0]
 [4 5 0]
 [7 8 9]]


In [23]:
# Inverse matrix
A = np.mat([[1, 2], [1, 0]])
invA = np.linalg.inv(A)
print('Matrix A')
print(A)
print('Inverse matrix A')
print(invA)

Matrix A
[[1 2]
 [1 0]]
Inverse matrix A
[[ 0.   1. ]
 [ 0.5 -0.5]]


## Matrix translation & Eigen Analysis

In [0]:
# library
import numpy as np

In [27]:
# Matrix transform
W = np.mat([[1/np.sqrt(2), 1/np.sqrt(2)], [-1/np.sqrt(2), 1/np.sqrt(2)]])
X = np.mat([[1], [2]])
print('Translation Matrix')
print(W)
print('Matrix A')
print(X)
print('Transformed Matrix')
print(np.matmul(W, X))

Translation Matrix
[[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]
Matrix A
[[1]
 [2]]
Transformed Matrix
[[2.12132034]
 [0.70710678]]


In [28]:
# Determinant
A = np.array([[1, 2], [3, 4]])
print(np.linalg.det(A))

-2.0000000000000004


In [29]:
# Eigenvalue & Eigenvector
A = np.mat([[3, 1], [1, 3]])
eigVal, eigVec = np.linalg.eig(A)
print(eigVal)
print(eigVec)

[4. 2.]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
